version: '3.4'
services:


  zookeeper1:
    image: confluentinc/cp-zookeeper:5.1.1
    hostname: zookeeper1
    restart: always
    ports:
      - 12181:12181
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 12181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper1:12888:13888;zookeeper2:22888:23888;zookeeper3:32888:33888


  zookeeper2:
    image: confluentinc/cp-zookeeper:5.1.1
    hostname: zookeeper2
    restart: always
    ports:
      - 22181:22181
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper1:12888:13888;zookeeper2:22888:23888;zookeeper3:32888:33888


  zookeeper3:
    image: confluentinc/cp-zookeeper:5.1.1
    hostname: zookeeper3
    restart: always
    ports:
      - 32181:32181
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper1:12888:13888;zookeeper2:22888:23888;zookeeper3:32888:33888


  kafka1:
    image: confluentinc/cp-kafka
    hostname: kafka1
    restart: always
    ports:
      - 19092:19092
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:12181,zookeeper2:22181,zookeeper3:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${DOCKER_HOST_IP}:19092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2


  kafka2:
    image: confluentinc/cp-kafka
    hostname: kafka2
    restart: always
    ports:
      - 29092:29092
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:12181,zookeeper2:22181,zookeeper3:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${DOCKER_HOST_IP}:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2


  kafka3:
    image: confluentinc/cp-kafka
    hostname: kafka3
    restart: always
    ports:
      - 39092:39092
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:12181,zookeeper2:22181,zookeeper3:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${DOCKER_HOST_IP}:39092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2


  kafka-rest-proxy:
    image: confluentinc/cp-kafka-rest:5.1.2
    hostname: kafka-rest-proxy
    restart: always
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_LISTENERS: http://kafka-rest-proxy:8082/
      KAFKA_REST_HOST_NAME: kafka-rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: PLAINTEXT://kafka1:19092
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
      - kafka1
      - kafka2
      - kafka3


  kafka-topics-ui:
    image: landoop/kafka-topics-ui:0.9.4
    hostname: kafka-topics-ui
    restart: always
    ports:
      - "8083:8000"
    environment:
      KAFKA_REST_PROXY_URL: "http://kafka-rest-proxy:8082/"
      PROXY: "true"
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
      - kafka1
      - kafka2
      - kafka3
      - kafka-rest-proxy
